name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What happened?
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
      value: "Not a bug happening!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other (If so, write the browser in the context area)
  - type: textarea
    id: images
    attributes:
      label: Images
      description: Add screenshots to help explaining the problem
      placeholder: Explain your problem
      value: ""
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Is there more we should know?
      value: "Something we didn't knew"
    validations:
      required: false